-- VEDA.VEDA_TBL_CP_ALARM definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_ALARM" 
   (	"FAB_NAME" VARCHAR2(5), 
	"RECORDID" NUMBER(10,0), 
	"LOTID" VARCHAR2(12), 
	"HISTDATE" DATE, 
	"PART" VARCHAR2(32), 
	"TECHNOLOGY" VARCHAR2(12), 
	"CUST_CODE" VARCHAR2(30), 
	"TEST_TYPE" VARCHAR2(32), 
	"OOR" VARCHAR2(2), 
	"OOR_LEVEL" VARCHAR2(8), 
	"BASELINE_YIELD" NUMBER, 
	"STDDEV" NUMBER, 
	"PE_OWNER" VARCHAR2(6), 
	"WAFERQTY" NUMBER(3,0), 
	"WAFERID_LIST" VARCHAR2(250), 
	"YIELD" NUMBER(10,4), 
	"FAILCATEGORY" VARCHAR2(32), 
	"MEASURETIME" DATE, 
	"USERCOMMENT" VARCHAR2(1024), 
	"MODIFYUSER" VARCHAR2(20), 
	"MODIFYTIME" DATE, 
	"TIMESTAMP" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_ALARM" ON "VEDA"."VEDA_TBL_CP_ALARM" ("RECORDID", "LOTID", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_ALARM" ADD CONSTRAINT "VEDA_PK_CP_ALARM" PRIMARY KEY ("RECORDID", "LOTID", "FAB_NAME")
  USING INDEX "VEDA"."VEDA_PK_CP_ALARM"  ENABLE;

CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_ALARM" ON "VEDA"."VEDA_TBL_CP_ALARM" ("RECORDID", "LOTID", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_ALARM" TO "EGUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_ALARM" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_ALARM" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_ALARM" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_ALARM" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_ALARM" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_ALARM" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_ALARM" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_ALARM" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_BATCH definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_BATCH" 
   (	"FAB_NAME" VARCHAR2(5), 
	"LOTID" VARCHAR2(12), 
	"TEST_TYPE" VARCHAR2(32), 
	"WAFERNO" NUMBER(3,0), 
	"TIMESTAMP" DATE, 
	"PART" VARCHAR2(32), 
	"TASKGROUP" VARCHAR2(50), 
	"BIN_DEF_NAME" VARCHAR2(80)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

CREATE INDEX "VEDA"."VEDA_IDX_CP_BATCH" ON "VEDA"."VEDA_TBL_CP_BATCH" ("TASKGROUP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT DELETE ON "VEDA"."VEDA_TBL_CP_BATCH" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_BATCH" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_BATCH" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_BATCH" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_BATCH" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_BATCH" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_BATCH" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_BATCH" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_BATCH_RESULT definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_BATCH_RESULT" 
   (	"FAB_NAME" VARCHAR2(5), 
	"FILENAME" VARCHAR2(200), 
	"GROSSDIE" NUMBER(38,0), 
	"BINVER" NUMBER(4,0), 
	"RESULT" VARCHAR2(2), 
	"TASKGROUP" VARCHAR2(50), 
	"LOGTIME" DATE, 
	"TIMESTAMP" DATE, 
	"LOADCMT" VARCHAR2(80)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

CREATE INDEX "VEDA"."VEDA_TBL_IDX_BATCH_RESULT" ON "VEDA"."VEDA_TBL_CP_BATCH_RESULT" ("TASKGROUP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT DELETE ON "VEDA"."VEDA_TBL_CP_BATCH_RESULT" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_BATCH_RESULT" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_BATCH_RESULT" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_BATCH_RESULT" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_BATCH_RESULT" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_BATCH_RESULT" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_BATCH_RESULT" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_BATCH_RESULT" TO "VEDAUSR";

COMMENT ON TABLE VEDA.VEDA_TBL_CP_BATCH_RESULT IS 'ISRM-1608869|不超過10000筆,依timestamp欄位保留1個月';


-- VEDA.VEDA_TBL_CP_BIN_DEFINITION definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" 
   (	"FAB_NAME" VARCHAR2(5), 
	"PART" VARCHAR2(32), 
	"BIN_DEF_NAME" VARCHAR2(80), 
	"BIN_NUMBER" NUMBER(38,0), 
	"BIN_NAME" VARCHAR2(5), 
	"DESCRIPTION" VARCHAR2(80), 
	"BIN_SPEC" VARCHAR2(2), 
	"GOOD_BIN_FLAG" NUMBER(38,0), 
	"CREATETIME" DATE, 
	"MODIFYTIME" DATE, 
	"HARD_BIN_NUMBER" NUMBER, 
	"HARD_BIN_NAME" VARCHAR2(5), 
	"HARD_BIN_DESCRIPTION" VARCHAR2(80), 
	"HARD_BIN_SPEC" VARCHAR2(2), 
	"HARD_GOOD_BIN_FLAG" NUMBER, 
	"TM_MIRR_FLAG" VARCHAR2(1), 
	"TM_SKIP_FLAG" VARCHAR2(1), 
	"TIMESTAMP" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_BIN_DEFINITION" ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" ("PART", "BIN_DEF_NAME", "BIN_NUMBER", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" ADD CONSTRAINT "VEDA_PK_CP_BIN_DEFINITION" PRIMARY KEY ("PART", "BIN_DEF_NAME", "BIN_NUMBER", "FAB_NAME")
  USING INDEX "VEDA"."VEDA_PK_CP_BIN_DEFINITION"  ENABLE;

CREATE INDEX "VEDA"."VEDA_IDX_CP_BD_TIME" ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" ("TIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_BIN_DEFINITION" ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" ("PART", "BIN_DEF_NAME", "BIN_NUMBER", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT DELETE ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "EDASUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "EDASUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "EDASUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "EDASUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "EGUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "VEDAPUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_BIN_DEFINITION" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_CONVERT_SET definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_CONVERT_SET" 
   (	"FAB_NAME" VARCHAR2(5), 
	"CUST_ID" NUMBER(4,0), 
	"TEST_FAB_ID" NUMBER(4,0), 
	"PART" VARCHAR2(32), 
	"CONVERT_TYPE" NUMBER(2,0), 
	"LOT_ID_START_ROW" NUMBER(4,0), 
	"LOT_ID_START_COL" NUMBER(4,0), 
	"LOT_ID_LEN" NUMBER(4,0), 
	"WAFER_ID_START_ROW" NUMBER(4,0), 
	"WAFER_ID_START_COL" NUMBER(4,0), 
	"WAFER_ID_LEN" NUMBER(4,0), 
	"PART_START_ROW_NO_CUT" NUMBER(4,0), 
	"PART_START_ROW" NUMBER(4,0), 
	"PART_START_COL" NUMBER(4,0), 
	"PART_LEN" NUMBER(4,0), 
	"BIN_DEF_START_ROW" NUMBER(4,0), 
	"BIN_DEF_START_COL" NUMBER(4,0), 
	"BIN_DEF_LEN" NUMBER(4,0), 
	"FTP_SERVER" VARCHAR2(50), 
	"FTP_FOLDER" VARCHAR2(50), 
	"FTP_USER" VARCHAR2(20), 
	"FTP_PASSWORD" VARCHAR2(50), 
	"BINMAP_START_ROW" NUMBER(4,0), 
	"BINMAP_END_ROW" NUMBER(4,0), 
	"BINMAP_START_COL" NUMBER(4,0), 
	"BINMAP_END_COL" NUMBER(4,0), 
	"BINLENGTH" NUMBER(4,0), 
	"BIN_CARRY" NUMBER(2,0), 
	"BREAK_TOKEN" VARCHAR2(16), 
	"MIRROR" NUMBER(2,0), 
	"EDATE_YEAR_START_ROW" NUMBER(4,0), 
	"EDATE_YEAR_START_COL" NUMBER(4,0), 
	"EDATE_YEAR_LEN" NUMBER(4,0), 
	"EDATE_MONTH_START_ROW" NUMBER(4,0), 
	"EDATE_MONTH_START_COL" NUMBER(4,0), 
	"EDATE_MONTH_LEN" NUMBER(4,0), 
	"EDATE_DAY_START_ROW" NUMBER(4,0), 
	"EDATE_DAY_START_COL" NUMBER(4,0), 
	"EDATE_DAY_LEN" NUMBER(4,0), 
	"EDATE_TIME_START_ROW" NUMBER(4,0), 
	"EDATE_TIME_START_COL" NUMBER(4,0), 
	"EDATE_TIME_LEN" NUMBER(4,0), 
	"BIN_DEF_NAME" VARCHAR2(80), 
	"COMMAND_FTP_GET" VARCHAR2(30), 
	"COMMAND_FTP_MODE" VARCHAR2(30), 
	"CP_NUMBER" NUMBER(2,0), 
	"INVERSE_ROTATE" NUMBER(2,0), 
	"CONVERTCOMMENT" VARCHAR2(500), 
	"SDATE_YEAR_START_ROW" NUMBER(4,0), 
	"SDATE_YEAR_START_COL" NUMBER(4,0), 
	"SDATE_YEAR_LEN" NUMBER(4,0), 
	"SDATE_MONTH_START_ROW" NUMBER(4,0), 
	"SDATE_MONTH_START_COL" NUMBER(4,0), 
	"SDATE_MONTH_LEN" NUMBER(4,0), 
	"SDATE_DAY_START_ROW" NUMBER(4,0), 
	"SDATE_DAY_START_COL" NUMBER(4,0), 
	"SDATE_DAY_LEN" NUMBER(4,0), 
	"SDATE_TIME_START_ROW" NUMBER(4,0), 
	"SDATE_TIME_START_COL" NUMBER(4,0), 
	"SDATE_TIME_LEN" NUMBER(4,0), 
	"CHECK_PART" VARCHAR2(256), 
	"LOTTAGNAME" VARCHAR2(15), 
	"WAFERTAGNAME" VARCHAR2(15), 
	"ENDDATETAGNAME" VARCHAR2(15), 
	"BINMAPTAGNAME" VARCHAR2(15), 
	"TEST_PROGRAM_START_ROW" NUMBER(4,0), 
	"TEST_PROGRAM_START_COLUMN" NUMBER(4,0), 
	"TEST_PROGRAM_LEN" NUMBER(4,0), 
	"RUNFLAG" NUMBER(1,0), 
	"HIMAXFLAT" VARCHAR2(3), 
	"RETURNFILELISTFLAG" NUMBER(1,0), 
	"BACKUPFTPFOLDER" VARCHAR2(300), 
	"TESTERID_START_ROW" NUMBER(4,0), 
	"TESTERID_START_COLUMN" NUMBER(4,0), 
	"TESTERID_LEN" NUMBER(4,0), 
	"PROBECARDID_START_ROW" NUMBER(4,0), 
	"PROBECARDID_START_COLUMN" NUMBER(4,0), 
	"PROBECARDID_LEN" NUMBER(4,0), 
	"CPNUMBERTAGNAME" VARCHAR2(15), 
	"OWNER" VARCHAR2(12), 
	"TIMESTAMP" DATE, 
	"PROD_ID" NUMBER(4,0), 
	"VERSION" NUMBER(4,0), 
	"GROUP_ID" VARCHAR2(11), 
	"PRIORITY" NUMBER(3,0), 
	"TURNKEY" VARCHAR2(1), 
	"TEST_PROGRAM_TAGNAME" VARCHAR2(15), 
	"TESTERID_TAGNAME" VARCHAR2(15), 
	"PROBECARDID_TAGNAME" VARCHAR2(15), 
	"RECDATE" DATE, 
	"RECNAME" VARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_CONVERT_SET" ON "VEDA"."VEDA_TBL_CP_CONVERT_SET" ("PART", "CUST_ID", "TEST_FAB_ID", "VERSION", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_CONVERT_SET" ADD CONSTRAINT "VEDA_PK_CP_CONVERT_SET" PRIMARY KEY ("PART", "CUST_ID", "TEST_FAB_ID", "VERSION", "FAB_NAME")
  USING INDEX "VEDA"."VEDA_PK_CP_CONVERT_SET"  ENABLE;

CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_CONVERT_SET" ON "VEDA"."VEDA_TBL_CP_CONVERT_SET" ("PART", "CUST_ID", "TEST_FAB_ID", "VERSION", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_CONVERT_SET" TO "EGUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_CONVERT_SET" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_CONVERT_SET" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_CONVERT_SET" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_CONVERT_SET" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_CONVERT_SET" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_CONVERT_SET" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_CONVERT_SET" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_CONVERT_SET" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_GROSSDIE definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_GROSSDIE" 
   (	"PRODUCT_NAME" VARCHAR2(32) NOT NULL ENABLE, 
	"GROSS_DIE" NUMBER(38,0), 
	"ACT_DIE" NUMBER(38,0), 
	"CHIP_SIZE_X" NUMBER, 
	"CHIP_SIZE_Y" NUMBER, 
	"REF_CHIP_SIZE_X" NUMBER, 
	"REF_CHIP_SIZE_Y" NUMBER, 
	"COMPLEXITY" NUMBER, 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"MODIFY_DATE" DATE DEFAULT SYSDATE, 
	"D0_FORMULA" VARCHAR2(64), 
	"FAB_NAME" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_GROSSDIE" ON "VEDA"."VEDA_TBL_CP_GROSSDIE" ("PRODUCT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_GROSSDIE" ADD CONSTRAINT "VEDA_PK_CP_GROSSDIE" PRIMARY KEY ("PRODUCT_NAME")
  USING INDEX "VEDA"."VEDA_PK_CP_GROSSDIE"  ENABLE;

CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_GROSSDIE" ON "VEDA"."VEDA_TBL_CP_GROSSDIE" ("PRODUCT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT DELETE ON "VEDA"."VEDA_TBL_CP_GROSSDIE" TO "EDASUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_GROSSDIE" TO "EDASUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_GROSSDIE" TO "EDASUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_GROSSDIE" TO "EDASUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_GROSSDIE" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_GROSSDIE" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_GROSSDIE" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_GROSSDIE" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_GROSSDIE" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_GROSSDIE" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_GROSSDIE" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_GROSSDIE" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_GROSSDIE_HIST definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" 
   (	"PRODUCT_NAME" VARCHAR2(32) NOT NULL ENABLE, 
	"GROSS_DIE" NUMBER(38,0), 
	"ACT_DIE" NUMBER(38,0), 
	"CHIP_SIZE_X" NUMBER, 
	"CHIP_SIZE_Y" NUMBER, 
	"REF_CHIP_SIZE_X" NUMBER, 
	"REF_CHIP_SIZE_Y" NUMBER, 
	"COMPLEXITY" NUMBER, 
	"PROCESS" VARCHAR2(10), 
	"CUSTOMERNAME" VARCHAR2(20), 
	"UNIT" VARCHAR2(10), 
	"CREATE_USER" VARCHAR2(20), 
	"CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"SRAM_RATIO" NUMBER DEFAULT 0, 
	"FAB_NAME" VARCHAR2(5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_GROSSDIE_HIST" ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" ("PRODUCT_NAME", "CREATE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" ADD CONSTRAINT "VEDA_PK_CP_GROSSDIE_HIST" PRIMARY KEY ("PRODUCT_NAME", "CREATE_DATE")
  USING INDEX "VEDA"."VEDA_PK_CP_GROSSDIE_HIST"  ENABLE;

CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_GROSSDIE_HIST" ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" ("PRODUCT_NAME", "CREATE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT DELETE ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" TO "EDASUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" TO "EDASUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" TO "EDASUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" TO "EDASUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_GROSSDIE_HIST" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_HWBIN_HEADER definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" 
   (	"FAB_NAME" VARCHAR2(5), 
	"PRODUCT_NAME" VARCHAR2(32) NOT NULL ENABLE, 
	"BIN_DEF_NAME" VARCHAR2(80) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(4) DEFAULT 1 NOT NULL ENABLE, 
	"CREATE_USER" VARCHAR2(20) NOT NULL ENABLE, 
	"CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_HWBIN_HEADER" ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" ("BIN_DEF_NAME", "VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" ADD CONSTRAINT "VEDA_PK_CP_HWBIN_HEADER" PRIMARY KEY ("BIN_DEF_NAME", "VERSION")
  USING INDEX "VEDA"."VEDA_PK_CP_HWBIN_HEADER"  ENABLE;

CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_HWBIN_HEADER" ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" ("BIN_DEF_NAME", "VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT DELETE ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" TO "EDASUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" TO "EDASUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" TO "EDASUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" TO "EDASUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_HWBIN_HEADER" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_HWBIN_HIST definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_HWBIN_HIST" 
   (	"BIN_NUMBER" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(80), 
	"BIN_SPEC" VARCHAR2(2), 
	"BIN_DEF_NAME" VARCHAR2(80) CONSTRAINT "NN_HB_BIN_DEF_NAME" NOT NULL ENABLE, 
	"VERSION" VARCHAR2(4) DEFAULT 1 NOT NULL ENABLE, 
	"CREATE_DATE" DATE DEFAULT sysdate, 
	 CONSTRAINT "CK_HB_BIN_NUMBER" CHECK (BIN_NUMBER BETWEEN 0 AND 999999) ENABLE, 
	 CONSTRAINT "NN_HB_DESCRIPTION" CHECK ("DESCRIPTION" IS NOT NULL) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_HWBIN_HIST" ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" ("BIN_DEF_NAME", "BIN_NUMBER", "VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_HWBIN_HIST" ADD CONSTRAINT "VEDA_PK_CP_HWBIN_HIST" PRIMARY KEY ("BIN_DEF_NAME", "BIN_NUMBER", "VERSION")
  USING INDEX "VEDA"."VEDA_PK_CP_HWBIN_HIST"  ENABLE;

CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_HWBIN_HIST" ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" ("BIN_DEF_NAME", "BIN_NUMBER", "VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT DELETE ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" TO "EDASUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" TO "EDASUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" TO "EDASUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" TO "EDASUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_HWBIN_HIST" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_INITCOOR definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_INITCOOR" 
   (	"FAB_NAME" VARCHAR2(5), 
	"CUSTOMER_ID" NUMBER(4,0), 
	"TEST_FAB_ID" NUMBER(4,0), 
	"PART" VARCHAR2(32), 
	"MIN_X" NUMBER, 
	"MIN_Y" NUMBER, 
	"MAX_X" NUMBER, 
	"MAX_Y" NUMBER, 
	"RUNFLAG" VARCHAR2(10), 
	"COMMENTS" VARCHAR2(256), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER" VARCHAR2(64), 
	"INSERT_TIME" DATE, 
	"INSERT_USER" VARCHAR2(64)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VEDA_TBL_TS"  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_INITCOOR" ON "VEDA"."VEDA_TBL_CP_INITCOOR" ("CUSTOMER_ID", "TEST_FAB_ID", "PART") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_INITCOOR" ADD CONSTRAINT "VEDA_PK_CP_INITCOOR" PRIMARY KEY ("CUSTOMER_ID", "TEST_FAB_ID", "PART")
  USING INDEX "VEDA"."VEDA_PK_CP_INITCOOR"  ENABLE;

CREATE INDEX "VEDA"."VEDA_IDX_CP_INITCOOR" ON "VEDA"."VEDA_TBL_CP_INITCOOR" ("RUNFLAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_INITCOOR" ON "VEDA"."VEDA_TBL_CP_INITCOOR" ("CUSTOMER_ID", "TEST_FAB_ID", "PART") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "VEDA_TBL_TS" ;

GRANT DELETE ON "VEDA"."VEDA_TBL_CP_INITCOOR" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_INITCOOR" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_INITCOOR" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_INITCOOR" TO "VEDAUSR";

COMMENT ON TABLE VEDA.VEDA_TBL_CP_INITCOOR IS 'ISRM-2500063|資料量約10萬筆|Config Data|針對CP產品By PART7,只保留一版';


-- VEDA.VEDA_TBL_CP_INIT_AXIS definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_INIT_AXIS" 
   (	"FAB_NAME" VARCHAR2(5), 
	"CUSTOMER_ID" VARCHAR2(4), 
	"TEST_FAB_ID" VARCHAR2(4), 
	"PRODUCT_ID" VARCHAR2(4), 
	"VERSION" VARCHAR2(4), 
	"PART" VARCHAR2(32), 
	"LOTID" VARCHAR2(32), 
	"WAFERNO" VARCHAR2(32), 
	"GOLDEN_STATUS" VARCHAR2(2), 
	"LB_AXIS_X" NUMBER(8,0), 
	"LB_AXIS_Y" NUMBER(8,0), 
	"RT_AXIS_X" NUMBER(8,0), 
	"RT_AXIS_Y" NUMBER(8,0), 
	"CREATOR" VARCHAR2(12), 
	"TIMESTAMP" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_INIT_AXIS" ON "VEDA"."VEDA_TBL_CP_INIT_AXIS" ("FAB_NAME", "CUSTOMER_ID", "TEST_FAB_ID", "PRODUCT_ID", "VERSION", "PART") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_INIT_AXIS" ADD CONSTRAINT "VEDA_PK_CP_INIT_AXIS" PRIMARY KEY ("FAB_NAME", "CUSTOMER_ID", "TEST_FAB_ID", "PRODUCT_ID", "VERSION", "PART")
  USING INDEX "VEDA"."VEDA_PK_CP_INIT_AXIS"  ENABLE;

CREATE INDEX "VEDA"."VEDA_IDX_CP_INIT_AXIS_PART" ON "VEDA"."VEDA_TBL_CP_INIT_AXIS" ("PART") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_INIT_AXIS" ON "VEDA"."VEDA_TBL_CP_INIT_AXIS" ("FAB_NAME", "CUSTOMER_ID", "TEST_FAB_ID", "PRODUCT_ID", "VERSION", "PART") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;

GRANT DELETE ON "VEDA"."VEDA_TBL_CP_INIT_AXIS" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_INIT_AXIS" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_INIT_AXIS" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_INIT_AXIS" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_INIT_AXIS_HIST definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_INIT_AXIS_HIST" 
   (	"FAB_NAME" VARCHAR2(5), 
	"CUSTOMER_ID" VARCHAR2(4), 
	"TEST_FAB_ID" VARCHAR2(4), 
	"PRODUCT_ID" VARCHAR2(4), 
	"VERSION" VARCHAR2(4), 
	"PART" VARCHAR2(32), 
	"LOTID" VARCHAR2(32), 
	"WAFERNO" VARCHAR2(32), 
	"GOLDEN_STATUS" VARCHAR2(2), 
	"LB_AXIS_X" NUMBER(8,0), 
	"LB_AXIS_Y" NUMBER(8,0), 
	"RT_AXIS_X" NUMBER(8,0), 
	"RT_AXIS_Y" NUMBER(8,0), 
	"CREATOR" VARCHAR2(12), 
	"TIMESTAMP" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VEDA_TBL_TS" ;

CREATE INDEX "VEDA"."VEDA_IDX_CP_INIT_AH_PART" ON "VEDA"."VEDA_TBL_CP_INIT_AXIS_HIST" ("PART") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE INDEX "VEDA"."VEDA_IDX_CP_INIT_AH_REC" ON "VEDA"."VEDA_TBL_CP_INIT_AXIS_HIST" ("CUSTOMER_ID", "TEST_FAB_ID", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "VEDA_TBL_TS" ;

GRANT DELETE ON "VEDA"."VEDA_TBL_CP_INIT_AXIS_HIST" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_INIT_AXIS_HIST" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_INIT_AXIS_HIST" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_INIT_AXIS_HIST" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_LOT definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_LOT" 
   (	"FAB_NAME" VARCHAR2(5), 
	"LOTID" VARCHAR2(12), 
	"TEST_TYPE" VARCHAR2(32), 
	"PART" VARCHAR2(32), 
	"PART6" VARCHAR2(6), 
	"MEASURETIME" DATE, 
	"TEST_PROGRAM" VARCHAR2(80), 
	"BIN_DEF_NAME" VARCHAR2(80), 
	"TEST_EQPID" VARCHAR2(50), 
	"CPOPERATOR" VARCHAR2(32), 
	"LOAD_BOARD" VARCHAR2(32), 
	"CPPROBECARD" VARCHAR2(32), 
	"TEST_VENDOR" VARCHAR2(32), 
	"WEEK" VARCHAR2(7), 
	"MONTH" VARCHAR2(7), 
	"TIMESTAMP" DATE, 
	"EMPL_ID" VARCHAR2(12), 
	"MPW_CD" VARCHAR2(4), 
	"MES_LOT_ID" VARCHAR2(12)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_LOT" ON "VEDA"."VEDA_TBL_CP_LOT" ("LOTID", "TEST_TYPE", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_LOT" ADD CONSTRAINT "VEDA_PK_CP_LOT" PRIMARY KEY ("LOTID", "TEST_TYPE", "FAB_NAME")
  USING INDEX "VEDA"."VEDA_PK_CP_LOT"  ENABLE;

CREATE INDEX "VEDA"."VEDA_IDX_CP_LOT_MTIME" ON "VEDA"."VEDA_TBL_CP_LOT" ("MEASURETIME", "PART6") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE INDEX "VEDA"."VEDA_IDX_CP_LOT_TIME" ON "VEDA"."VEDA_TBL_CP_LOT" ("TIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_LOT" ON "VEDA"."VEDA_TBL_CP_LOT" ("LOTID", "TEST_TYPE", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT" TO "EDASUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT" TO "EGUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_LOT" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_LOT" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_LOT" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT" TO "VEDAPUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_LOT" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_LOT" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_LOT" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_LOT_PTN_DTL definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_LOT_PTN_DTL" 
   (	"PTN_KEY" VARCHAR2(30) NOT NULL ENABLE, 
	"CLASSIFY_RESULT" VARCHAR2(20) NOT NULL ENABLE, 
	"CLASSIFY_RATE" NUMBER NOT NULL ENABLE, 
	"CLASSIFY_DATE" DATE NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_LOT_PTN_DTL" ON "VEDA"."VEDA_TBL_CP_LOT_PTN_DTL" ("PTN_KEY", "CLASSIFY_RESULT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_LOT_PTN_DTL" ADD CONSTRAINT "VEDA_PK_CP_LOT_PTN_DTL" PRIMARY KEY ("PTN_KEY", "CLASSIFY_RESULT")
  USING INDEX "VEDA"."VEDA_PK_CP_LOT_PTN_DTL"  ENABLE;

CREATE INDEX "VEDA"."VEDA_IDX_CP_LOT_PTN_DTL" ON "VEDA"."VEDA_TBL_CP_LOT_PTN_DTL" ("CLASSIFY_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_LOT_PTN_DTL" ON "VEDA"."VEDA_TBL_CP_LOT_PTN_DTL" ("PTN_KEY", "CLASSIFY_RESULT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_PTN_DTL" TO "EDASUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_PTN_DTL" TO "VEDAPUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_LOT_PTN_DTL" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_LOT_PTN_DTL" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_PTN_DTL" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_LOT_PTN_DTL" TO "VEDAUSR";

COMMENT ON TABLE VEDA.VEDA_TBL_CP_LOT_PTN_DTL IS 'ISRM-1806138 168萬筆/1年 依CLASSIFY_DATE欄位保留1年 Loader: merge insert寫入同時delete過舊資料';


-- VEDA.VEDA_TBL_CP_LOT_PTN_INFO definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_LOT_PTN_INFO" 
   (	"PTN_KEY" VARCHAR2(30) NOT NULL ENABLE, 
	"LOTID" VARCHAR2(12) NOT NULL ENABLE, 
	"TEST_TYPE" VARCHAR2(5) NOT NULL ENABLE, 
	"PART6" VARCHAR2(6) NOT NULL ENABLE, 
	"PART7" VARCHAR2(7) NOT NULL ENABLE, 
	"CLASSIFY_DATE" DATE NOT NULL ENABLE, 
	"IMAGEPATH" VARCHAR2(200) NOT NULL ENABLE, 
	"MODEL_VER" VARCHAR2(16) NOT NULL ENABLE, 
	"RETICLE_ISSUE" VARCHAR2(20), 
	"TOP" NUMBER, 
	"BIN" VARCHAR2(5), 
	"PATTERN_ISSUE" VARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_LOT_PTN_INFO" ON "VEDA"."VEDA_TBL_CP_LOT_PTN_INFO" ("PTN_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_LOT_PTN_INFO" ADD CONSTRAINT "VEDA_PK_CP_LOT_PTN_INFO" PRIMARY KEY ("PTN_KEY")
  USING INDEX "VEDA"."VEDA_PK_CP_LOT_PTN_INFO"  ENABLE;

CREATE INDEX "VEDA"."VEDA_IDX_CP_LOT_PTN_INFO" ON "VEDA"."VEDA_TBL_CP_LOT_PTN_INFO" ("LOTID", "TEST_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_LOT_PTN_INFO" ON "VEDA"."VEDA_TBL_CP_LOT_PTN_INFO" ("PTN_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_PTN_INFO" TO "EDASUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_PTN_INFO" TO "VEDAPUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_LOT_PTN_INFO" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_LOT_PTN_INFO" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_PTN_INFO" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_LOT_PTN_INFO" TO "VEDAUSR";

COMMENT ON TABLE VEDA.VEDA_TBL_CP_LOT_PTN_INFO IS 'ISRM-1806138 8萬筆/1年 依CLASSIFY_DATE欄位保留1年 Loader: merge insert寫入同時delete過舊資料';


-- VEDA.VEDA_TBL_CP_LOT_SUM definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_LOT_SUM" 
   (	"FAB_NAME" VARCHAR2(5), 
	"LOTID" VARCHAR2(12), 
	"TEST_TYPE" VARCHAR2(32), 
	"MEASURETIME" DATE, 
	"WEEK" VARCHAR2(7), 
	"MONTH" VARCHAR2(7), 
	"WAFERCOUNT" NUMBER(3,0), 
	"GROSS_DIE" NUMBER(38,0), 
	"NUM_GOOD_DIE" NUMBER, 
	"BIN0" NUMBER, 
	"BIN1" NUMBER, 
	"BIN2" NUMBER, 
	"BIN3" NUMBER, 
	"BIN4" NUMBER, 
	"BIN5" NUMBER, 
	"BIN6" NUMBER, 
	"BIN7" NUMBER, 
	"BIN8" NUMBER, 
	"BIN9" NUMBER, 
	"BIN10" NUMBER, 
	"BIN11" NUMBER, 
	"BIN12" NUMBER, 
	"BIN13" NUMBER, 
	"BIN14" NUMBER, 
	"BIN15" NUMBER, 
	"BIN16" NUMBER, 
	"BIN17" NUMBER, 
	"BIN18" NUMBER, 
	"BIN19" NUMBER, 
	"BIN20" NUMBER, 
	"BIN21" NUMBER, 
	"BIN22" NUMBER, 
	"BIN23" NUMBER, 
	"BIN24" NUMBER, 
	"BIN25" NUMBER, 
	"BIN26" NUMBER, 
	"BIN27" NUMBER, 
	"BIN28" NUMBER, 
	"BIN29" NUMBER, 
	"BIN30" NUMBER, 
	"BIN31" NUMBER, 
	"BIN32" NUMBER, 
	"BIN33" NUMBER, 
	"BIN34" NUMBER, 
	"BIN35" NUMBER, 
	"BIN36" NUMBER, 
	"BIN37" NUMBER, 
	"BIN38" NUMBER, 
	"BIN39" NUMBER, 
	"BIN40" NUMBER, 
	"BIN41" NUMBER, 
	"BIN42" NUMBER, 
	"BIN43" NUMBER, 
	"BIN44" NUMBER, 
	"BIN45" NUMBER, 
	"BIN46" NUMBER, 
	"BIN47" NUMBER, 
	"BIN48" NUMBER, 
	"BIN49" NUMBER, 
	"BIN50" NUMBER, 
	"BIN51" NUMBER, 
	"BIN52" NUMBER, 
	"BIN53" NUMBER, 
	"BIN54" NUMBER, 
	"BIN55" NUMBER, 
	"BIN56" NUMBER, 
	"BIN57" NUMBER, 
	"BIN58" NUMBER, 
	"BIN59" NUMBER, 
	"BIN60" NUMBER, 
	"BIN61" NUMBER, 
	"BIN62" NUMBER, 
	"BIN63" NUMBER, 
	"BIN64" NUMBER, 
	"BIN65" NUMBER, 
	"BIN66" NUMBER, 
	"BIN67" NUMBER, 
	"BIN68" NUMBER, 
	"BIN69" NUMBER, 
	"BIN70" NUMBER, 
	"BIN71" NUMBER, 
	"BIN72" NUMBER, 
	"BIN73" NUMBER, 
	"BIN74" NUMBER, 
	"BIN75" NUMBER, 
	"BIN76" NUMBER, 
	"BIN77" NUMBER, 
	"BIN78" NUMBER, 
	"BIN79" NUMBER, 
	"BIN80" NUMBER, 
	"BIN81" NUMBER, 
	"BIN82" NUMBER, 
	"BIN83" NUMBER, 
	"BIN84" NUMBER, 
	"BIN85" NUMBER, 
	"BIN86" NUMBER, 
	"BIN87" NUMBER, 
	"BIN88" NUMBER, 
	"BIN89" NUMBER, 
	"BIN90" NUMBER, 
	"BIN91" NUMBER, 
	"BIN92" NUMBER, 
	"BIN93" NUMBER, 
	"BIN94" NUMBER, 
	"BIN95" NUMBER, 
	"BIN96" NUMBER, 
	"BIN97" NUMBER, 
	"BIN98" NUMBER, 
	"BIN99" NUMBER, 
	"CREATETIME" DATE, 
	"MODIFYTIME" DATE, 
	"CP_FORMAT" VARCHAR2(10), 
	"D0_AVERAGE_FIT" NUMBER, 
	"D0_MEDIAN_FIT" NUMBER, 
	"NUM_TESTED_DIE" NUMBER, 
	"NUM_FUNCTIONAL_DIE" NUMBER, 
	"RANGE_INDEX" NUMBER, 
	"MARK_FLAG" VARCHAR2(7), 
	"YIELD" NUMBER(10,4), 
	"TIMESTAMP" DATE, 
	"FINAL_GOOD_DIE_SQX" NUMBER(22,0), 
	"GOOD_DIE_MAX" NUMBER(22,0), 
	"GOOD_DIE_MIN" NUMBER(22,0), 
	"GOOD_DIE_SQX" NUMBER(22,0), 
	"GOOD_X_REPAIR" NUMBER(22,0), 
	"IS_STACK_WAFER" VARCHAR2(1), 
	"KILL_DIE_CNT" NUMBER(22,0), 
	"OPEN_DIE_CNT" NUMBER(22,0), 
	"RECVRY_DIE_CNT" NUMBER(22,0), 
	"REPAIR_DIE_CNT" NUMBER(22,0), 
	"REPAIR_DIE_SQX" NUMBER(22,0), 
	"REPROBE_DIE_CNT" NUMBER(22,0), 
	"VI_DIE_CNT" NUMBER(22,0), 
	"YLD_TYPE" VARCHAR2(9), 
	"MES_LOT_ID" VARCHAR2(12), 
	"SHIPPING_YIELD" NUMBER, 
	"SHIPPING_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_LOT_SUM" ON "VEDA"."VEDA_TBL_CP_LOT_SUM" ("LOTID", "TEST_TYPE", "RANGE_INDEX", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_LOT_SUM" ADD CONSTRAINT "VEDA_PK_CP_LOT_SUM" PRIMARY KEY ("LOTID", "TEST_TYPE", "RANGE_INDEX", "FAB_NAME")
  USING INDEX "VEDA"."VEDA_PK_CP_LOT_SUM"  ENABLE;

CREATE INDEX "VEDA"."VEDA_IDX_CP_LOT_SUM_TIME" ON "VEDA"."VEDA_TBL_CP_LOT_SUM" ("TIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_LOT_SUM" ON "VEDA"."VEDA_TBL_CP_LOT_SUM" ("LOTID", "TEST_TYPE", "RANGE_INDEX", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_SUM" TO "EDASUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_SUM" TO "EGUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_LOT_SUM" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_LOT_SUM" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_SUM" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_LOT_SUM" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_SUM" TO "VEDAPUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_LOT_SUM" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_LOT_SUM" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_SUM" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_LOT_SUM" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_LOT_SUM_SYNC definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_LOT_SUM_SYNC" 
   (	"LOTID" VARCHAR2(12), 
	"TEST_TYPE" VARCHAR2(32), 
	"TIMESTAMP" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_LOT_SUM_SYNC" ON "VEDA"."VEDA_TBL_CP_LOT_SUM_SYNC" ("LOTID", "TEST_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_LOT_SUM_SYNC" ADD CONSTRAINT "VEDA_PK_CP_LOT_SUM_SYNC" PRIMARY KEY ("LOTID", "TEST_TYPE")
  USING INDEX "VEDA"."VEDA_PK_CP_LOT_SUM_SYNC"  ENABLE;

CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_LOT_SUM_SYNC" ON "VEDA"."VEDA_TBL_CP_LOT_SUM_SYNC" ("LOTID", "TEST_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_SUM_SYNC" TO "EGUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_LOT_SUM_SYNC" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_LOT_SUM_SYNC" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_SUM_SYNC" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_LOT_SUM_SYNC" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_LOT_SUM_SYNC" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_LOT_SUM_SYNC" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_LOT_SUM_SYNC" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_LOT_SUM_SYNC" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_PTN_REDEFINE definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_PTN_REDEFINE" 
   (	"FAB_NAME" VARCHAR2(5) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(16) NOT NULL ENABLE, 
	"IMG_PATH" VARCHAR2(200) NOT NULL ENABLE, 
	"REDEF_PTN" VARCHAR2(20) NOT NULL ENABLE, 
	"REDEF_DATE" DATE NOT NULL ENABLE, 
	"RETRAIN_FLAG" VARCHAR2(1)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VEDA_TBL_TS" ;

GRANT DELETE ON "VEDA"."VEDA_TBL_CP_PTN_REDEFINE" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_PTN_REDEFINE" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_PTN_REDEFINE" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_PTN_REDEFINE" TO "VEDAUSR";

COMMENT ON TABLE VEDA.VEDA_TBL_CP_PTN_REDEFINE IS 'ISRM-1812520 約50000筆/3months 依CLOSEDATE時間欄位保留3 months AP TEAM自行purge ';


-- VEDA.VEDA_TBL_CP_RAW definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_RAW" 
   (	"FAB_NAME" VARCHAR2(5), 
	"LOTID" VARCHAR2(64), 
	"TEST_TYPE" VARCHAR2(32), 
	"WAFERNO" NUMBER(3,0), 
	"WAFERID" VARCHAR2(12), 
	"MEASURETIME" DATE, 
	"WEEK" VARCHAR2(7), 
	"MONTH" VARCHAR2(7), 
	"Y_COORD" NUMBER(38,0), 
	"VIEW_FLAG" NUMBER, 
	"CREATETIME" DATE, 
	"MODIFYTIME" DATE, 
	"FIMER_STR" VARCHAR2(512), 
	"TIMESTAMP" DATE, 
	"BIN_STR" CLOB, 
	"VI_STR" CLOB, 
	"BIN_TYPE_STR" CLOB, 
	"MES_LOT_ID" VARCHAR2(64)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
 LOB ("BIN_STR") STORE AS SECUREFILE (
  TABLESPACE "VEDA_TBL_TS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("VI_STR") STORE AS SECUREFILE (
  TABLESPACE "VEDA_TBL_TS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("BIN_TYPE_STR") STORE AS SECUREFILE (
  TABLESPACE "VEDA_TBL_TS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "VEDA"."SYS_IL0000115969C00017$$" ON "VEDA"."VEDA_TBL_CP_RAW" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "VEDA"."SYS_IL0000115969C00016$$" ON "VEDA"."VEDA_TBL_CP_RAW" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "VEDA"."SYS_IL0000115969C00015$$" ON "VEDA"."VEDA_TBL_CP_RAW" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "VEDA"."VEDA_INDEX_CP_RAW" ON "VEDA"."VEDA_TBL_CP_RAW" ("FAB_NAME", "LOTID", "TEST_TYPE", "WAFERNO", "Y_COORD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT DELETE ON "VEDA"."VEDA_TBL_CP_RAW" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_RAW" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_RAW" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_RAW" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_RAW_TEMP definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_RAW_TEMP" 
   (	"FAB_NAME" VARCHAR2(5), 
	"LOTID" VARCHAR2(12), 
	"TEST_TYPE" VARCHAR2(32), 
	"WAFERNO" NUMBER(3,0), 
	"WAFERID" VARCHAR2(12), 
	"MEASURETIME" DATE, 
	"WEEK" VARCHAR2(7), 
	"MONTH" VARCHAR2(7), 
	"Y_COORD" NUMBER(38,0), 
	"VIEW_FLAG" NUMBER, 
	"CREATETIME" DATE, 
	"MODIFYTIME" DATE, 
	"FIMER_STR" VARCHAR2(512), 
	"TIMESTAMP" DATE, 
	"BIN_STR" CLOB, 
	"VI_STR" CLOB, 
	"BIN_TYPE_STR" CLOB, 
	"MES_LOT_ID" VARCHAR2(12)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VEDA_TBL_TS" 
 LOB ("BIN_STR") STORE AS BASICFILE (
  TABLESPACE "VEDA_TBL_TS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("VI_STR") STORE AS BASICFILE (
  TABLESPACE "VEDA_TBL_TS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("BIN_TYPE_STR") STORE AS BASICFILE (
  TABLESPACE "VEDA_TBL_TS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING ) ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_RAW_TEMP" ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" ("LOTID", "TEST_TYPE", "WAFERNO", "Y_COORD", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_RAW_TEMP" ADD CONSTRAINT "VEDA_PK_CP_RAW_TEMP" PRIMARY KEY ("LOTID", "TEST_TYPE", "WAFERNO", "Y_COORD", "FAB_NAME")
  USING INDEX "VEDA"."VEDA_PK_CP_RAW_TEMP"  ENABLE;

CREATE UNIQUE INDEX "VEDA"."SYS_IL0000091156C00017$$" ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "VEDA"."SYS_IL0000091156C00016$$" ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "VEDA"."SYS_IL0000091156C00015$$" ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_RAW_TEMP" ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" ("LOTID", "TEST_TYPE", "WAFERNO", "Y_COORD", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" TO "EGUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_RAW_TEMP" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_SAMPLE_RATE_SET_OL definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_SAMPLE_RATE_SET_OL" 
   (	"FAB_NAME" VARCHAR2(5), 
	"PART6" VARCHAR2(6), 
	"FULL_DIE_COUNT" NUMBER(8,0), 
	"SAMPLE_DIE_COUNT" NUMBER(8,0), 
	"MODIFYTIME" DATE, 
	"TIMESTAMP" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS"  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_SAMPLE_RATE_SET_OL" ON "VEDA"."VEDA_TBL_CP_SAMPLE_RATE_SET_OL" ("PART6", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE( INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_SAMPLE_RATE_SET_OL" ADD CONSTRAINT "VEDA_PK_CP_SAMPLE_RATE_SET_OL" PRIMARY KEY ("PART6", "FAB_NAME")
  USING INDEX "VEDA"."VEDA_PK_CP_SAMPLE_RATE_SET_OL"  ENABLE;

CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_SAMPLE_RATE_SET_OL" ON "VEDA"."VEDA_TBL_CP_SAMPLE_RATE_SET_OL" ("PART6", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE( INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_SAMPLE_RATE_SET_OL" TO "EGUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_SAMPLE_RATE_SET_OL" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_SAMPLE_RATE_SET_OL" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_SAMPLE_RATE_SET_OL" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_SAMPLE_RATE_SET_OL" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_SAMPLE_RATE_SET_OL" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_SAMPLE_RATE_SET_OL" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_SAMPLE_RATE_SET_OL" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_SAMPLE_RATE_SET_OL" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_TEST_PROG_OLD definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_TEST_PROG_OLD" 
   (	"FAB_NAME" VARCHAR2(5), 
	"PART" VARCHAR2(32), 
	"BIN_DEF_NAME" VARCHAR2(80), 
	"TEST_PROGRAM" VARCHAR2(80), 
	"CP_FT_FLAG" VARCHAR2(5), 
	"NOTCH_FLAG" VARCHAR2(5), 
	"CREATETIME" DATE, 
	"MODIFYTIME" DATE, 
	"TIMESTAMP" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS"  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_TEST_PROG_OLD" ON "VEDA"."VEDA_TBL_CP_TEST_PROG_OLD" ("PART", "BIN_DEF_NAME", "TEST_PROGRAM", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE( INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_TEST_PROG_OLD" ADD CONSTRAINT "VEDA_PK_CP_TEST_PROG_OLD" PRIMARY KEY ("PART", "BIN_DEF_NAME", "TEST_PROGRAM", "FAB_NAME")
  USING INDEX "VEDA"."VEDA_PK_CP_TEST_PROG_OLD"  ENABLE;

CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_TEST_PROG_OLD" ON "VEDA"."VEDA_TBL_CP_TEST_PROG_OLD" ("PART", "BIN_DEF_NAME", "TEST_PROGRAM", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE( INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_TEST_PROG_OLD" TO "EGUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_TEST_PROG_OLD" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_TEST_PROG_OLD" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_TEST_PROG_OLD" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_TEST_PROG_OLD" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_TEST_PROG_OLD" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_TEST_PROG_OLD" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_TEST_PROG_OLD" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_TEST_PROG_OLD" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_WAFER definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_WAFER" 
   (	"FAB_NAME" VARCHAR2(5), 
	"LOTID" VARCHAR2(12), 
	"TEST_TYPE" VARCHAR2(32), 
	"WAFERNO" NUMBER(3,0), 
	"WAFERID" VARCHAR2(12), 
	"PART" VARCHAR2(32), 
	"PART6" VARCHAR2(6), 
	"MEASURETIME" DATE, 
	"TEST_PROGRAM" VARCHAR2(80), 
	"BIN_DEF_NAME" VARCHAR2(80), 
	"TEST_EQPID" VARCHAR2(50), 
	"CPOPERATOR" VARCHAR2(32), 
	"LOAD_BOARD" VARCHAR2(32), 
	"CPPROBECARD" VARCHAR2(32), 
	"TEST_VENDOR" VARCHAR2(32), 
	"WEEK" VARCHAR2(7), 
	"MONTH" VARCHAR2(7), 
	"TIMESTAMP" DATE, 
	"CREATETIME" DATE, 
	"MES_LOT_ID" VARCHAR2(12)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_WAFER" ON "VEDA"."VEDA_TBL_CP_WAFER" ("LOTID", "TEST_TYPE", "WAFERNO", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_WAFER" ADD CONSTRAINT "VEDA_PK_CP_WAFER" PRIMARY KEY ("LOTID", "TEST_TYPE", "WAFERNO", "FAB_NAME")
  USING INDEX "VEDA"."VEDA_PK_CP_WAFER"  ENABLE;

CREATE INDEX "VEDA"."VEDA_IDX_CP_WAFER_MTIME" ON "VEDA"."VEDA_TBL_CP_WAFER" ("MEASURETIME", "PART6") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE INDEX "VEDA"."VEDA_IDX_CP_WAFER_TIME" ON "VEDA"."VEDA_TBL_CP_WAFER" ("TIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_WAFER" ON "VEDA"."VEDA_TBL_CP_WAFER" ("LOTID", "TEST_TYPE", "WAFERNO", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER" TO "EGUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_WAFER" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_WAFER" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_WAFER" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_WAFER" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_WAFER" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_WAFER" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_WAFER_BIN definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_WAFER_BIN" 
   (	"FAB_NAME" VARCHAR2(5) NOT NULL ENABLE, 
	"LOTID" VARCHAR2(12) NOT NULL ENABLE, 
	"TEST_TYPE" VARCHAR2(12) NOT NULL ENABLE, 
	"WAFERNO" NUMBER(3,0) NOT NULL ENABLE, 
	"WAFERID" VARCHAR2(12) NOT NULL ENABLE, 
	"BIN_NO" NUMBER NOT NULL ENABLE, 
	"BIN_TYPE" VARCHAR2(1), 
	"BIN_CNT" NUMBER NOT NULL ENABLE, 
	"BIN_CNT_VI" NUMBER, 
	"MEASURETIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"GROSS_DIE" NUMBER, 
	"RECVRY_DIE_CNT" NUMBER, 
	"REPROBE_DIE_CNT" NUMBER, 
	"KILL_DIE_CNT" NUMBER, 
	"CREATETIME" DATE, 
	"MODIFYTIME" DATE, 
	"ZONEID_BINCNT_STRING_3C" VARCHAR2(128), 
	"ZONEID_BINCNT_STRING_4C" VARCHAR2(128), 
	"ZONEID_BINCNT_STRING_8P" VARCHAR2(128), 
	"ZONEID_BINCNT_STRING_9S" VARCHAR2(128), 
	"ZONE2_BIN_RATIO" NUMBER, 
	"ZONE1_BIN_RATIO" NUMBER, 
	"ZONE3_BIN_RATIO" NUMBER, 
	"ZONE4_BIN_RATIO" NUMBER, 
	"NORMAL_LOT_BAYE_VAL" VARCHAR2(28), 
	"ALL_LOT_BAYE_VAL" VARCHAR2(28), 
	"ZONEID_BINCNT_STRING_DIGIT" NUMBER, 
	"TIMESTAMP" DATE, 
	"MES_LOT_ID" VARCHAR2(12), 
	"ZONEID_BINCNT_STRING_5S" VARCHAR2(128), 
	"ZONEID_BINCNT_STRING_5W" VARCHAR2(128), 
	"ZONEID_BINCNT_STRING_9W" VARCHAR2(128)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_WAFER_BIN" ON "VEDA"."VEDA_TBL_CP_WAFER_BIN" ("LOTID", "TEST_TYPE", "WAFERNO", "BIN_NO", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_WAFER_BIN" ADD CONSTRAINT "VEDA_PK_CP_WAFER_BIN" PRIMARY KEY ("LOTID", "TEST_TYPE", "WAFERNO", "BIN_NO", "FAB_NAME")
  USING INDEX "VEDA"."VEDA_PK_CP_WAFER_BIN"  ENABLE;

CREATE INDEX "VEDA"."VEDA_IDX_CP_WAFER_BIN_TIME" ON "VEDA"."VEDA_TBL_CP_WAFER_BIN" ("TIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_WAFER_BIN" ON "VEDA"."VEDA_TBL_CP_WAFER_BIN" ("LOTID", "TEST_TYPE", "WAFERNO", "BIN_NO", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_BIN" TO "EGUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_WAFER_BIN" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_WAFER_BIN" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_BIN" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_WAFER_BIN" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_WAFER_BIN" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_WAFER_BIN" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_BIN" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_WAFER_BIN" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_WAFER_PTN_DTL definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_WAFER_PTN_DTL" 
   (	"PTN_KEY" VARCHAR2(30) NOT NULL ENABLE, 
	"CLASSIFY_RESULT" VARCHAR2(20) NOT NULL ENABLE, 
	"CLASSIFY_RATE" NUMBER NOT NULL ENABLE, 
	"CLASSIFY_DATE" DATE NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_WAFER_PTN_DTL" ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_DTL" ("PTN_KEY", "CLASSIFY_RESULT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_WAFER_PTN_DTL" ADD CONSTRAINT "VEDA_PK_CP_WAFER_PTN_DTL" PRIMARY KEY ("PTN_KEY", "CLASSIFY_RESULT")
  USING INDEX "VEDA"."VEDA_PK_CP_WAFER_PTN_DTL"  ENABLE;

CREATE INDEX "VEDA"."VEDA_IDX_CP_WAFER_PTN_DTL" ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_DTL" ("CLASSIFY_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_WAFER_PTN_DTL" ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_DTL" ("PTN_KEY", "CLASSIFY_RESULT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_DTL" TO "EDASUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_DTL" TO "VEDAPUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_DTL" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_DTL" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_DTL" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_DTL" TO "VEDAUSR";

COMMENT ON TABLE VEDA.VEDA_TBL_CP_WAFER_PTN_DTL IS 'ISRM-1806138 3549萬筆/1年 依CLASSIFY_DATE欄位保留1年 Loader: merge insert寫入同時delete過舊資料';


-- VEDA.VEDA_TBL_CP_WAFER_PTN_INFO definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_WAFER_PTN_INFO" 
   (	"PTN_KEY" VARCHAR2(30) NOT NULL ENABLE, 
	"LOTID" VARCHAR2(12) NOT NULL ENABLE, 
	"WAFERNO" NUMBER(2,0) NOT NULL ENABLE, 
	"TEST_TYPE" VARCHAR2(5) NOT NULL ENABLE, 
	"PART6" VARCHAR2(6) NOT NULL ENABLE, 
	"PART7" VARCHAR2(7) NOT NULL ENABLE, 
	"CLASSIFY_DATE" DATE NOT NULL ENABLE, 
	"IMAGEPATH" VARCHAR2(200) NOT NULL ENABLE, 
	"MODEL_VER" VARCHAR2(16) NOT NULL ENABLE, 
	"RETICLE_ISSUE" VARCHAR2(20), 
	"TOP" NUMBER, 
	"BIN" VARCHAR2(5), 
	"PATTERN_ISSUE" VARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_WAFER_PTN_INFO" ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_INFO" ("PTN_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_WAFER_PTN_INFO" ADD CONSTRAINT "VEDA_PK_CP_WAFER_PTN_INFO" PRIMARY KEY ("PTN_KEY")
  USING INDEX "VEDA"."VEDA_PK_CP_WAFER_PTN_INFO"  ENABLE;

CREATE INDEX "VEDA"."VEDA_IDX_CP_WAFER_PTN_INFO" ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_INFO" ("LOTID", "WAFERNO", "TEST_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_WAFER_PTN_INFO" ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_INFO" ("PTN_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_INFO" TO "EDASUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_INFO" TO "VEDAPUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_INFO" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_INFO" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_INFO" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_WAFER_PTN_INFO" TO "VEDAUSR";

COMMENT ON TABLE VEDA.VEDA_TBL_CP_WAFER_PTN_INFO IS 'ISRM-1806138 169萬筆/1年 依CLASSIFY_DATE欄位保留1年 Loader: merge insert寫入同時delete過舊資料';


-- VEDA.VEDA_TBL_CP_WAFER_SUM definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_WAFER_SUM" 
   (	"FAB_NAME" VARCHAR2(5), 
	"LOTID" VARCHAR2(12), 
	"TEST_TYPE" VARCHAR2(32), 
	"WAFERNO" NUMBER(3,0), 
	"WAFERID" VARCHAR2(12), 
	"MEASURETIME" DATE, 
	"WEEK" VARCHAR2(7), 
	"MONTH" VARCHAR2(7), 
	"CP_RTN_LOTID" VARCHAR2(12), 
	"VIEW_FLAG" NUMBER(38,0), 
	"DATA_SOURCE" VARCHAR2(1), 
	"GROSS_DIE" NUMBER(38,0), 
	"NUM_GOOD_DIE" NUMBER, 
	"BIN0" NUMBER, 
	"BIN1" NUMBER, 
	"BIN2" NUMBER, 
	"BIN3" NUMBER, 
	"BIN4" NUMBER, 
	"BIN5" NUMBER, 
	"BIN6" NUMBER, 
	"BIN7" NUMBER, 
	"BIN8" NUMBER, 
	"BIN9" NUMBER, 
	"BIN10" NUMBER, 
	"BIN11" NUMBER, 
	"BIN12" NUMBER, 
	"BIN13" NUMBER, 
	"BIN14" NUMBER, 
	"BIN15" NUMBER, 
	"BIN16" NUMBER, 
	"BIN17" NUMBER, 
	"BIN18" NUMBER, 
	"BIN19" NUMBER, 
	"BIN20" NUMBER, 
	"BIN21" NUMBER, 
	"BIN22" NUMBER, 
	"BIN23" NUMBER, 
	"BIN24" NUMBER, 
	"BIN25" NUMBER, 
	"BIN26" NUMBER, 
	"BIN27" NUMBER, 
	"BIN28" NUMBER, 
	"BIN29" NUMBER, 
	"BIN30" NUMBER, 
	"BIN31" NUMBER, 
	"BIN32" NUMBER, 
	"BIN33" NUMBER, 
	"BIN34" NUMBER, 
	"BIN35" NUMBER, 
	"BIN36" NUMBER, 
	"BIN37" NUMBER, 
	"BIN38" NUMBER, 
	"BIN39" NUMBER, 
	"BIN40" NUMBER, 
	"BIN41" NUMBER, 
	"BIN42" NUMBER, 
	"BIN43" NUMBER, 
	"BIN44" NUMBER, 
	"BIN45" NUMBER, 
	"BIN46" NUMBER, 
	"BIN47" NUMBER, 
	"BIN48" NUMBER, 
	"BIN49" NUMBER, 
	"BIN50" NUMBER, 
	"BIN51" NUMBER, 
	"BIN52" NUMBER, 
	"BIN53" NUMBER, 
	"BIN54" NUMBER, 
	"BIN55" NUMBER, 
	"BIN56" NUMBER, 
	"BIN57" NUMBER, 
	"BIN58" NUMBER, 
	"BIN59" NUMBER, 
	"BIN60" NUMBER, 
	"BIN61" NUMBER, 
	"BIN62" NUMBER, 
	"BIN63" NUMBER, 
	"BIN64" NUMBER, 
	"BIN65" NUMBER, 
	"BIN66" NUMBER, 
	"BIN67" NUMBER, 
	"BIN68" NUMBER, 
	"BIN69" NUMBER, 
	"BIN70" NUMBER, 
	"BIN71" NUMBER, 
	"BIN72" NUMBER, 
	"BIN73" NUMBER, 
	"BIN74" NUMBER, 
	"BIN75" NUMBER, 
	"BIN76" NUMBER, 
	"BIN77" NUMBER, 
	"BIN78" NUMBER, 
	"BIN79" NUMBER, 
	"BIN80" NUMBER, 
	"BIN81" NUMBER, 
	"BIN82" NUMBER, 
	"BIN83" NUMBER, 
	"BIN84" NUMBER, 
	"BIN85" NUMBER, 
	"BIN86" NUMBER, 
	"BIN87" NUMBER, 
	"BIN88" NUMBER, 
	"BIN89" NUMBER, 
	"BIN90" NUMBER, 
	"BIN91" NUMBER, 
	"BIN92" NUMBER, 
	"BIN93" NUMBER, 
	"BIN94" NUMBER, 
	"BIN95" NUMBER, 
	"BIN96" NUMBER, 
	"BIN97" NUMBER, 
	"BIN98" NUMBER, 
	"BIN99" NUMBER, 
	"CREATETIME" DATE, 
	"MODIFYTIME" DATE, 
	"D0_FIT" NUMBER, 
	"NUM_TESTED_DIE" NUMBER, 
	"NUM_FUNCTIONAL_DIE" NUMBER, 
	"TL_X_COORD" NUMBER, 
	"TL_Y_COORD" NUMBER, 
	"BR_X_COORD" NUMBER, 
	"BR_Y_COORD" NUMBER, 
	"LOADTIME" DATE, 
	"RANGE_INDEX" NUMBER, 
	"MARK_FLAG" VARCHAR2(7), 
	"YIELD" NUMBER(10,4), 
	"TIMESTAMP" DATE, 
	"OPEN_DIE_CNT" NUMBER(22,0), 
	"RECVRY_DIE_CNT" NUMBER(22,0), 
	"REPROBE_DIE_CNT" NUMBER(22,0), 
	"REPAIR_DIE_CNT" NUMBER(22,0), 
	"KILL_DIE_CNT" NUMBER(22,0), 
	"VI_DIE_CNT" NUMBER(22,0), 
	"YLD_TYPE" VARCHAR2(9), 
	"MAP_X_AXIS_MAX" NUMBER(22,0), 
	"MAP_X_AXIS_MIN" NUMBER(22,0), 
	"MAP_Y_AXIS_MAX" NUMBER(22,0), 
	"MAP_Y_AXIS_MIN" NUMBER(22,0), 
	"ZONEID_DIECNT_STRING_3C" VARCHAR2(128), 
	"ZONEID_DIECNT_STRING_4C" VARCHAR2(128), 
	"ZONEID_DIECNT_STRING_8P" VARCHAR2(128), 
	"ZONEID_DIECNT_STRING_9S" VARCHAR2(128), 
	"MES_LOT_ID" VARCHAR2(12), 
	"ZONEID_DIECNT_STRING_5S" VARCHAR2(128), 
	"ZONEID_DIECNT_STRING_5W" VARCHAR2(128), 
	"ZONEID_DIECNT_STRING_9W" VARCHAR2(128), 
	"SHIPPING_YIELD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_WAFER_SUM" ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" ("LOTID", "TEST_TYPE", "WAFERNO", "RANGE_INDEX", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_WAFER_SUM" ADD CONSTRAINT "VEDA_PK_CP_WAFER_SUM" PRIMARY KEY ("LOTID", "TEST_TYPE", "WAFERNO", "RANGE_INDEX", "FAB_NAME")
  USING INDEX "VEDA"."VEDA_PK_CP_WAFER_SUM"  ENABLE;

CREATE INDEX "VEDA"."VEDA_IDX_CP_WAFER_SUM_TIME" ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" ("TIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE INDEX "VEDA"."VEDA_IDX_CP_WAFER_SUM_WAFERID" ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" ("WAFERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_WAFER_SUM" ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" ("LOTID", "TEST_TYPE", "WAFERNO", "RANGE_INDEX", "FAB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" TO "EDASUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" TO "EGUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" TO "VEDAPUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_WAFER_SUM" TO "VEDAUSR";


-- VEDA.VEDA_TBL_CP_ZONE definition

CREATE TABLE "VEDA"."VEDA_TBL_CP_ZONE" 
   (	"FAB_NAME" VARCHAR2(5) NOT NULL ENABLE, 
	"PART6" VARCHAR2(6) NOT NULL ENABLE, 
	"LOTID" VARCHAR2(12) NOT NULL ENABLE, 
	"TEST_TYPE" VARCHAR2(32) NOT NULL ENABLE, 
	"WAFERNO" NUMBER(3,0) NOT NULL ENABLE, 
	"Y_COORD" NUMBER(38,0) NOT NULL ENABLE, 
	"STR_3C" CLOB, 
	"STR_4C" CLOB, 
	"STR_8P" CLOB, 
	"STR_9S" CLOB, 
	"STR_5W" CLOB, 
	"STR_9W" CLOB, 
	"TIMESTAMP" DATE, 
	"STR_5S" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
 LOB ("STR_3C") STORE AS BASICFILE (
  TABLESPACE "VEDA_TBL_TS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("STR_4C") STORE AS BASICFILE (
  TABLESPACE "VEDA_TBL_TS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("STR_8P") STORE AS BASICFILE (
  TABLESPACE "VEDA_TBL_TS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("STR_9S") STORE AS BASICFILE (
  TABLESPACE "VEDA_TBL_TS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("STR_5W") STORE AS BASICFILE (
  TABLESPACE "VEDA_TBL_TS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("STR_9W") STORE AS BASICFILE (
  TABLESPACE "VEDA_TBL_TS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("STR_5S") STORE AS BASICFILE (
  TABLESPACE "VEDA_TBL_TS" ENABLE STORAGE IN ROW CHUNK 32768 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_ZONE" ON "VEDA"."VEDA_TBL_CP_ZONE" ("PART6", "Y_COORD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;
ALTER TABLE "VEDA"."VEDA_TBL_CP_ZONE" ADD CONSTRAINT "VEDA_PK_CP_ZONE" PRIMARY KEY ("PART6", "Y_COORD")
  USING INDEX "VEDA"."VEDA_PK_CP_ZONE"  ENABLE;

CREATE UNIQUE INDEX "VEDA"."SYS_IL0000091523C00014$$" ON "VEDA"."VEDA_TBL_CP_ZONE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 204800 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "VEDA"."SYS_IL0000091523C00012$$" ON "VEDA"."VEDA_TBL_CP_ZONE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 204800 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "VEDA"."SYS_IL0000091523C00011$$" ON "VEDA"."VEDA_TBL_CP_ZONE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 204800 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "VEDA"."SYS_IL0000091523C00010$$" ON "VEDA"."VEDA_TBL_CP_ZONE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 204800 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "VEDA"."SYS_IL0000091523C00009$$" ON "VEDA"."VEDA_TBL_CP_ZONE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 204800 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "VEDA"."SYS_IL0000091523C00008$$" ON "VEDA"."VEDA_TBL_CP_ZONE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 204800 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "VEDA"."SYS_IL0000091523C00007$$" ON "VEDA"."VEDA_TBL_CP_ZONE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 204800 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "VEDA"."VEDA_PK_CP_ZONE" ON "VEDA"."VEDA_TBL_CP_ZONE" ("PART6", "Y_COORD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VEDA_TBL_TS" ;

GRANT DELETE ON "VEDA"."VEDA_TBL_CP_ZONE" TO "ETLUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_ZONE" TO "ETLUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_ZONE" TO "ETLUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_ZONE" TO "ETLUSR";
  GRANT DELETE ON "VEDA"."VEDA_TBL_CP_ZONE" TO "VEDAUSR";
  GRANT INSERT ON "VEDA"."VEDA_TBL_CP_ZONE" TO "VEDAUSR";
  GRANT SELECT ON "VEDA"."VEDA_TBL_CP_ZONE" TO "VEDAUSR";
  GRANT UPDATE ON "VEDA"."VEDA_TBL_CP_ZONE" TO "VEDAUSR";
