from setuptools import setup, find_packages

setup(
    name="sas-viya-python-framework",
    version="1.0.0",
    description="Comprehensive Python development framework for SAS Viya integration",
    author="Your Name",
    author_email="your.email@company.com",
    packages=find_packages(),
    install_requires=[
        "saspy",
        "swat", 
        "sasctl",
        "pandas",
        "numpy",
        "scikit-learn",
        "matplotlib",
        "seaborn",
        "jupyter",
        "plotly",
        "dash",
        "xgboost",
        "lightgbm",
        "tensorflow",
        "keras",
        "pyyaml",
        "requests",
        "joblib"
    ],
    python_requires=">=3.7",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)